analyzer:
  exclude:
    - build/**
    - apps/**/build/**
    - packages/**/build/**
    - node_modules/**
    - tools/knowledge_ingestion/node_modules/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
